### ISSUE TITLE
测试自己建立的数据集时遇到了一些问题

### ISSUE THREAD

**Issue by hanyi997** [silverbulletmdc/PVEN#24]
作者您好，我参考veri776数据集的命名格式重新建立了query和gallery，并按照readme的步骤重新生成了pkl文件和解析后的mask文件。但进行测试时遇到了以下错误：

The test feature is normalized
Calculate distance matrixs...
Calculate local distances...
Saving results...
Eval...
Generating worker pools
2.6813037395477295
  0%|                                                                                                                           | 0/17 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/vehicle_reid_pytorch-1.0-py3.8.egg/vehicle_reid_pytorch/metrics/eval_reid.py", line 136, in worker
    AP, cmc = calc_AP(orig_cmc)
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/vehicle_reid_pytorch-1.0-py3.8.egg/vehicle_reid_pytorch/metrics/eval_reid.py", line 212, in calc_AP
    raise ValueError
ValueError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 528, in <module>
    clk()
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 392, in eval
    eval_(model, cfg.test.device, valid_loader, query_length,
  File "main.py", line 444, in eval_
    metric_output = metric.compute(split=split)
  File "/home/ubuntu/users/hanyi/PVEN-vehicle_reid/examples/parsing_reid/math_tools.py", line 212, in compute
    cmc= eval_func_mp(distmat + self.lambda_ * (local_distmat ** 2), q_pids, g_pids, q_camids, g_camids,
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/vehicle_reid_pytorch-1.0-py3.8.egg/vehicle_reid_pytorch/metrics/eval_reid.py", line 106, in eval_func_mp
    for r in tqdm(res, total=num_q):
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 420, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ubuntu/users/hanyi/anaconda3/envs/py3.8/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError

**Comment by lunuanw** [comment]
请问解决了吗，我也是这个问题

**Comment by silverbulletmdc** [comment]
出现这个错误是因为query所属的id没有出现在gallery里，我直接让他报错了。可以先过滤一遍数据，确保gallery中至少存在一张query数据。否则测试出来的结果没有意义。

**Comment by CarrieYpi** [comment]
> 出现这个错误是因为query所属的id没有出现在gallery里，我直接让他报错了。可以先过滤一遍数据，确保gallery中至少存在一张query数据。否则测试出来的结果没有意义。

你好，请问运行了python generate_masks.py这个文件后，生成的图片是全黑的是不是有问题呢？

**Comment by silverbulletmdc** [comment]
> > 出现这个错误是因为query所属的id没有出现在gallery里，我直接让他报错了。可以先过滤一遍数据，确保gallery中至少存在一张query数据。否则测试出来的结果没有意义。
> 
> 你好，请问运行了python generate_masks.py这个文件后，生成的图片是全黑的是不是有问题呢？

是正常的。因为我用1，2，3来代表不同的mask值，反映到图像里都是黑白的（最大255）。想看实际的形状可以用matplotlib画一下。
