### ISSUE TITLE
RuntimeError: inython train_parsing.py --train-set trainval --masks-path ../outputs/veri776_parsing3165 --image-path C:\Users\kuruparans\Desktop\adhi\VeRi/image_train

### ISSUE THREAD

**Issue by kuruparan** [silverbulletmdc/PVEN#6]
(pven) C:\Users\kuruparans\Desktop\adhi\PVEN\examples\parsing>python train_parsing.py --train-set trainval --masks-path ../outputs/veri776_parsing3165 --image-path C:\Users\kuruparans\Desktop\adhi\VeRi/image_train

Epoch: 0
train:   0%|                                                                                                      | 0/396 [00:00<?, ?it/s]
Epoch: 0
train:   0%|                                                                                                      | 0/396 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
train:   0%|                                                                                                      | 0/396 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "train_parsing.py", line 111, in <module>
    train_logs = train_epoch.run(train_loader)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\segmentation_models_pytorch\utils\train.py", line 45, in run
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 114, in _main
        for x, y in iterator:prepare(preparation_data)

  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\tqdm\std.py", line 1130, in __iter__
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\runpy.py", line 96, in _run_module_code
        mod_name, mod_spec, pkg_name, script_name)for obj in iterable:

  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\runpy.py", line 85, in _run_code
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    exec(code, run_globals)
  File "C:\Users\kuruparans\Desktop\adhi\PVEN\examples\parsing\train_parsing.py", line 111, in <module>
    train_logs = train_epoch.run(train_loader)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\segmentation_models_pytorch\utils\train.py", line 45, in run
    for x, y in iterator:
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\tqdm\std.py", line 1130, in __iter__
    for obj in iterable:
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\process.py", line 105, in start
    w.start()
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\process.py", line 105, in start
        self._popen = self._Popen(self)self._popen = self._Popen(self)

  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 223, in _Popen
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 223, in _Popen
        return _default_context.get_context().Process._Popen(process_obj)return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 322, in _Popen
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    return Popen(process_obj)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
        reduction.dump(process_obj, to_child)prep_data = spawn.get_preparation_data(process_obj._name)

  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\reduction.py", line 60, in dump
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

(pven) C:\Users\kuruparans\Desktop\adhi\PVEN\examples\parsing>

**Comment by kuruparan** [comment]
solved with __name__ == '__main__':

**Comment by 9527-csroad** [comment]
​Hi, could you tell me which file you changed?​ I have the same question.​
