### ISSUE TITLE
AttributeError: Can't pickle local object 'AlbuRandomErasing.<locals>.wrapper'

### ISSUE THREAD

**Issue by kuruparan** [silverbulletmdc/PVEN#7]
File "main.py", line 460, in <module>
    clk()
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 232, in train
    for iter, batch in enumerate(train_loader):
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'AlbuRandomErasing.<locals>.wrapper'

(pven) C:\Users\kuruparans\Desktop\adhi\PVEN\examples\parsing_reid>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\kuruparans\Anaconda3\envs\pven\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by silverbulletmdc** [comment]
The code hasn't been tested in Windows. It seems like the albumentation module cannot be dumped to pickle during parallel processing.

**Comment by 15718073787** [comment]
Have you solved it? I met the same problem

**Comment by 15718073787** [comment]
Have you solved it? I met the same problem

**Comment by 15718073787** [comment]
Have you solved it? I met the same problem
